### ISSUE TITLE
Aggregation and composition

### ISSUE THREAD

**Issue by LudlowCode** [isaaccomputerscience/isaac-code-samples#25]
Hi, and thanks for the brilliant work that you do. FYI [a blackjack game involving agg and compo](https://github.com/isaaccomputerscience/isaac-code-samples/tree/main/object-oriented-programming/blackjack-game) is linked to here: https://isaaccomputerscience.org/concepts/prog_oop_inheritance_polymorphism?examBoard=ocr&stage=a_level but it's gone or been moved presumably. Thanks, Dave.

**Comment by dianedowling** [comment]
Thanks for your kind comments. We did plan to add the resource but it wasn't really right educationally so decided not to. We didn't realise that the link had been added. Thanks for notifying us.
