### ISSUE TITLE
Missing getting setters on certain files

### ISSUE THREAD

**Issue by f1nn1711** [isaaccomputerscience/isaac-code-samples#27]
On this file:
- https://github.com/isaaccomputerscience/isaac-code-samples/blob/main/data-structures/linked-list/python/linked_list_OOP.py

When accessing certain attributes, it uses getters and setters and in other cases it doesn't.
This should be updated to follow best practices and reduce confusion for students on what the best practices are.

**Comment by alexparry** [comment]
Thank you for raising this issue. I've added getters and setters to the LinkedList class now too.
